{% set name = "gsheetsdb" %}
{% set version = "0.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7cd622e4baf50d8656ee45ad7bb811d814539cc2d2ac079ad0345c9231135111

build:
  noarch: python
  entry_points:
    - gsheetsdb = gsheetsdb.console:main
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - google-auth
    - moz-sql-parser
    - requests >=2.20.0
    - six

test:
  imports:
    - gsheetsdb

about:
  home: https://github.com/betodealmeida/gsheets-db-api
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: This module allows you to query Google Spreadsheets using SQL.

extra:
  recipe-maintainers:
    - tim-werner
